export const missionsSeed = [
  {
    key: 'PRIMEIRA_FOTO',
    titulo: 'Primeira Foto',
    descricao: 'Adicione uma foto principal ao perfil do seu terreiro. Perfis com foto recebem 70% mais visitas.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'fotoUrl' },
    rewardAxScore: 10,
    rewardTrustScore: 2,
    ordem: 1,
  },
  {
    key: 'DESCRICAO_COMPLETA',
    titulo: 'Conte Sua História',
    descricao: 'Escreva a história do seu terreiro. Descreva a missão, a tradição e o que torna sua casa especial.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'descricaoLonga' },
    rewardAxScore: 8,
    rewardTrustScore: 3,
    ordem: 2,
  },
  {
    key: 'HORARIO_FUNCIONAMENTO',
    titulo: 'Horários de Funcionamento',
    descricao: 'Informe os dias e horários de funcionamento. Isso ajuda visitantes a planejarem sua visita.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'horarioFuncionamento' },
    rewardAxScore: 5,
    rewardTrustScore: 1,
    ordem: 3,
  },
  {
    key: 'REDES_SOCIAIS',
    titulo: 'Conecte Suas Redes',
    descricao: 'Conecte pelo menos uma rede social. Perfis com redes sociais têm 3x mais engajamento.',
    categoria: 'PERFIL',
    requisitos: { type: 'anyField', fields: ['instagram', 'facebook', 'whatsapp'] },
    rewardAxScore: 5,
    rewardTrustScore: 2,
    ordem: 4,
  },
  {
    key: 'PRIMEIRO_EVENTO',
    titulo: 'Primeiro Evento',
    descricao: 'Crie seu primeiro evento. Giras, festas e palestras atraem a comunidade para seu terreiro.',
    categoria: 'EVENTOS',
    requisitos: { type: 'count', model: 'eventos', min: 1 },
    rewardAxScore: 10,
    rewardTrustScore: 3,
    ordem: 5,
  },
  {
    key: 'GALERIA_FOTOS',
    titulo: 'Galeria de Fotos',
    descricao: 'Adicione 5 ou mais fotos à galeria do seu terreiro. Isso aumenta a confiança dos visitantes.',
    categoria: 'PERFIL',
    requisitos: { type: 'count', model: 'fotos', min: 5 },
    rewardAxScore: 8,
    rewardTrustScore: 3,
    ordem: 6,
  },
  {
    key: 'ADICIONAR_TELEFONE',
    titulo: 'Telefone de Contato',
    descricao: 'Adicione um telefone de contato. Visitantes preferem ligar antes de visitar.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'telefone' },
    rewardAxScore: 5,
    rewardTrustScore: 1,
    ordem: 7,
  },
  {
    key: 'ENDERECO_COMPLETO',
    titulo: 'Endereço Completo',
    descricao: 'Certifique-se de que o endereço e as coordenadas estão corretos para aparecer no mapa.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'latitude' },
    rewardAxScore: 5,
    rewardTrustScore: 1,
    ordem: 8,
  },
  {
    key: 'PRIMEIRO_CURSO',
    titulo: 'Primeiro Curso',
    descricao: 'Crie um curso. Compartilhe conhecimento e fortaleça sua comunidade.',
    categoria: 'CURSOS',
    requisitos: { type: 'count', model: 'cursos', min: 1 },
    rewardAxScore: 10,
    rewardTrustScore: 3,
    ordem: 9,
  },
  {
    key: 'ACAO_SOCIAL',
    titulo: 'Ação Social',
    descricao: 'Registre uma ação social do seu terreiro. Mostre o impacto positivo na comunidade.',
    categoria: 'SOCIAL',
    requisitos: { type: 'count', model: 'acoesSociais', min: 1 },
    rewardAxScore: 10,
    rewardTrustScore: 4,
    ordem: 10,
  },
  {
    key: 'COMPARTILHAR_PERFIL',
    titulo: 'Compartilhe o Perfil',
    descricao: 'Compartilhe o link do seu perfil nas redes sociais. Quanto mais visitas, maior sua relevância.',
    categoria: 'DIVULGACAO',
    requisitos: { type: 'action', action: 'shared_profile' },
    rewardAxScore: 3,
    rewardTrustScore: 1,
    ordem: 11,
  },
  {
    key: 'RESPONDER_AVALIACAO',
    titulo: 'Responda Avaliações',
    descricao: 'Responda a uma avaliação. Isso mostra que você se importa com a opinião dos visitantes.',
    categoria: 'ENGAJAMENTO',
    requisitos: { type: 'count', model: 'avaliacaoRespostas', min: 1 },
    rewardAxScore: 5,
    rewardTrustScore: 2,
    ordem: 12,
  },
  {
    key: 'SELO_ACESSIBILIDADE',
    titulo: 'Informações de Acessibilidade',
    descricao: 'Marque as informações de acessibilidade do seu terreiro. Inclusão é fundamental.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'acessibilidade' },
    rewardAxScore: 5,
    rewardTrustScore: 2,
    ordem: 13,
  },
  {
    key: 'ANUNCIAR_TRADICAO',
    titulo: 'Declare Sua Tradição',
    descricao: 'Especifique a tradição religiosa do seu terreiro. Isso ajuda na descoberta por fiéis.',
    categoria: 'PERFIL',
    requisitos: { type: 'field', field: 'tradicao' },
    rewardAxScore: 3,
    rewardTrustScore: 1,
    ordem: 14,
  },
  {
    key: 'ATINGIR_TRUST_30',
    titulo: 'Trust Score 30+',
    descricao: 'Alcance Trust Score 30+. Continue melhorando seu perfil para ganhar a confiança da comunidade.',
    categoria: 'CRESCIMENTO',
    requisitos: { type: 'trustScore', min: 30 },
    rewardAxScore: 15,
    rewardTrustScore: 0,
    ordem: 15,
  },
];

export const achievementsSeed = [
  {
    key: 'BEM_VINDO',
    titulo: 'Bem-Vindo ao AxéMap',
    descricao: 'Você criou seu perfil e iniciou sua jornada no AxéMap.',
    icone: '🎉',
    categoria: 'INICIACAO',
    requisitos: { type: 'automatic' },
    rewardAxScore: 5,
    ordem: 1,
  },
  {
    key: 'PERFIL_COMPLETO',
    titulo: 'Perfil Completo',
    descricao: 'Você preencheu todas as informações do seu perfil. Agora brilha com luz própria!',
    icone: '⭐',
    categoria: 'PERFIL',
    requisitos: { type: 'completeness', min: 100 },
    rewardAxScore: 20,
    ordem: 2,
  },
  {
    key: 'FOTOGRAFO',
    titulo: 'Fotógrafo',
    descricao: 'Você adicionou mais de 10 fotos à galeria do seu terreiro.',
    icone: '📸',
    categoria: 'PERFIL',
    requisitos: { type: 'count', model: 'fotos', min: 10 },
    rewardAxScore: 10,
    ordem: 3,
  },
  {
    key: 'AGITADOR_CULTURAL',
    titulo: 'Agitador Cultural',
    descricao: 'Você criou 5 ou mais eventos. Seu terreiro é um polo cultural!',
    icone: '📅',
    categoria: 'EVENTOS',
    requisitos: { type: 'count', model: 'eventos', min: 5 },
    rewardAxScore: 15,
    ordem: 4,
  },
  {
    key: 'CONECTADO',
    titulo: 'Totalmente Conectado',
    descricao: 'Você vinculou Instagram, Facebook e WhatsApp ao seu perfil.',
    icone: '🔗',
    categoria: 'PERFIL',
    requisitos: { type: 'allFields', fields: ['instagram', 'facebook', 'whatsapp'] },
    rewardAxScore: 10,
    ordem: 5,
  },
  {
    key: 'VERIFICADO',
    titulo: 'Perfil Verificado',
    descricao: 'Seu terreiro passou pelo processo de verificação. Confiança máxima!',
    icone: '✅',
    categoria: 'VERIFICACAO',
    requisitos: { type: 'verification', minLevel: 'DOCUMENTAL' },
    rewardAxScore: 25,
    ordem: 6,
  },
  {
    key: 'POPULAR',
    titulo: 'Popular',
    descricao: 'Seu terreiro recebeu 50 favoritos. A comunidade está de olho!',
    icone: '❤️',
    categoria: 'ENGAJAMENTO',
    requisitos: { type: 'favoritos', min: 50 },
    rewardAxScore: 15,
    ordem: 7,
  },
  {
    key: 'BEM_AVALIADO',
    titulo: 'Bem Avaliado',
    descricao: 'Seu perfil mantém média 4.5+ com 10 ou mais avaliações.',
    icone: '🌟',
    categoria: 'ENGAJAMENTO',
    requisitos: { type: 'avaliacoes', minMedia: 4.5, minCount: 10 },
    rewardAxScore: 20,
    ordem: 8,
  },
  {
    key: 'ENSINANTE',
    titulo: 'Mestre',
    descricao: 'Você criou 3 ou mais cursos. O saber é a luz que ilumina caminhos!',
    icone: '📚',
    categoria: 'CURSOS',
    requisitos: { type: 'count', model: 'cursos', min: 3 },
    rewardAxScore: 15,
    ordem: 9,
  },
  {
    key: 'SOCIAL',
    titulo: 'Transformador Social',
    descricao: 'Você registrou 3 ou mais ações sociais. Axé é amor em movimento!',
    icone: '🤝',
    categoria: 'SOCIAL',
    requisitos: { type: 'count', model: 'acoesSociais', min: 3 },
    rewardAxScore: 15,
    ordem: 10,
  },
  {
    key: 'VETERANO',
    titulo: 'Veterano',
    descricao: 'Seu perfil está ativo há mais de 1 ano. Constância é força!',
    icone: '⏳',
    categoria: 'CRESCIMENTO',
    requisitos: { type: 'age', minDays: 365 },
    rewardAxScore: 10,
    ordem: 11,
  },
  {
    key: 'LENDARIO',
    titulo: 'Lendário',
    descricao: 'Trust Score lendário! Você é referência na plataforma.',
    icone: '🏆',
    categoria: 'CRESCIMENTO',
    requisitos: { type: 'trustScore', min: 80 },
    rewardAxScore: 30,
    ordem: 12,
  },
];
