export enum UserRole {
  VISITOR = 'VISITOR',
  PRACTITIONER = 'PRACTITIONER',
  DIRIGENTE = 'DIRIGENTE',
  OGA = 'OGA',
  EKEDI = 'EKEDI',
  FILHO_DE_SANTO = 'FILHO_DE_SANTO',
  MEMBER = 'MEMBER',
  CO_ADMIN = 'CO_ADMIN',
  CURATOR = 'CURATOR',
  MODERATOR = 'MODERATOR',
  VERIFIER = 'VERIFIER',
  SUPPORT = 'SUPPORT',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum TerreiroStatus {
  RASCUNHO = 'RASCUNHO',
  PENDENTE_REVISAO = 'PENDENTE_REVISAO',
  EM_REVISAO = 'EM_REVISAO',
  AGUARDANDO_DIRIGENTE = 'AGUARDANDO_DIRIGENTE',
  PUBLICADO = 'PUBLICADO',
  EM_EDICAO = 'EM_EDICAO',
  RECUSADO = 'RECUSADO',
  BLOQUEADO = 'BLOQUEADO',
  ARQUIVADO = 'ARQUIVADO',
  SUSPENSO = 'SUSPENSO',
  VERIFICADO = 'VERIFICADO',
}

export enum Tradicao {
  UMBANDA = 'UMBANDA',
  CANDOMBLE_KETU = 'CANDOMBLE_KETU',
  CANDOMBLE_ANGOLA = 'CANDOMBLE_ANGOLA',
  CANDOMBLE_JEJE = 'CANDOMBLE_JEJE',
  JUREMA = 'JUREMA',
  TAMBOR_DE_MINA = 'TAMBOR_DE_MINA',
  XANGO = 'XANGO',
}

export enum EventType {
  GIRA = 'GIRA',
  TOQUE = 'TOQUE',
  FESTA_RELIGIOSA = 'FESTA_RELIGIOSA',
  PALESTRA = 'PALESTRA',
  CURSO = 'CURSO',
  DESENVOLVIMENTO_MEDIUNICO = 'DESENVOLVIMENTO_MEDIUNICO',
  ACAO_SOCIAL = 'ACAO_SOCIAL',
}

export enum TrustScoreLevel {
  INITIATE = 'INITIATE',
  EMERGING = 'EMERGING',
  ESTABLISHED = 'ESTABLISHED',
  AUTHORITY = 'AUTHORITY',
  LEGENDARY = 'LEGENDARY',
}

export enum VerificationLevel {
  BASICO = 'BASICO',
  DOCUMENTAL = 'DOCUMENTAL',
  COMUNITARIO = 'COMUNITARIO',
  AVANCADO = 'AVANCADO',
  COMPLETO = 'COMPLETO',
}

export enum ProductCategory {
  VELA = 'VELA',
  ERVA = 'ERVA',
  DEFUMADOR = 'DEFUMADOR',
  GUIA = 'GUIA',
  FIO_DE_CONTA = 'FIO_DE_CONTA',
  VESTUARIO = 'VESTUARIO',
  INSTRUMENTO = 'INSTRUMENTO',
  IMAGEM_SACRA = 'IMAGEM_SACRA',
  LIVRO = 'LIVRO',
  SERVICO = 'SERVICO',
}
