-- AlterEnum
ALTER TYPE "OrganizationType" ADD VALUE 'PESQUISADOR';
ALTER TYPE "OrganizationType" ADD VALUE 'GRUPO_DE_PESQUISA';
ALTER TYPE "OrganizationType" ADD VALUE 'TEMPLO';
ALTER TYPE "OrganizationType" ADD VALUE 'ORGANIZACAO_INTERNACIONAL';